name: Continuous Delivery

on:
  push:
    branches:
      - master
      - test
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    name: デプロイ
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Decrypt .env file
        run: ./.github/scripts/decrypt_env.sh
        env:
          ENV_CREDENTIALS: ${{ secrets.ENV_CREDENTIALS }}
      - name: Decrypt firebase_secret file
        run: ./.github/scripts/decrypt_secret.sh
        env:
          ENV_CREDENTIALS: ${{ secrets.ENV_CREDENTIALS }}

      - name: Set Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm i

      - name: build 【test】
        if: github.ref == 'refs/heads/test'
        run: npm run build:test
      - name: Deploy GAE 【test】
        if: github.ref == 'refs/heads/test'
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}
          deliverables: appTest.yaml

      - name: build 【production】
        if: github.ref == 'refs/heads/master'
        run: npm run build:production
      - name: Deploy GAE 【production】
        if: github.ref == 'refs/heads/master'
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS_JSON }}
          deliverables: app.yaml
