name: Continuous Delivery

on:
  push:
    branches:
      - test
# --
jobs:
  deploy:
    name: デプロイ
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Decrypt .env file
        run: ./.github/scripts/decrypt_env.sh
        env:
          ENV_CREDENTIALS: ${{ secrets.ENV_CREDENTIALS }}
      - name: Decrypt firebase_secret file
        run: ./.github/scripts/decrypt_secret.sh
        env:
          ENV_CREDENTIALS: ${{ secrets.ENV_CREDENTIALS }}
      - name: Set Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm i
      - name: build test
        run: npm run build:test
      - name: Deploy GAE
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS_JSON }} # 成功
          deliverables: appTest.yaml
